### ISSUE TITLE
css error

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#100]
Hi @mcristaldo 
please, kindly reply in the next hour, cause I really want to advance

css validation is giving error here
https://github.com/jfoclpf/autocosts/blob/master/src/css/style.css#L133

is this syntax ok? 

```css
.radio_tab_container input[type='radio']:checked + label {background-color: black; color: white;
    .radio_tab_container label {color: white; background-color: black;}
 }
```

I never saw it, but when I try to change it, the form doesn't show ok
