### ISSUE TITLE
logo in IE is too big

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#113]
The logo in IE is too big

In line 15 of `css/style.css` replace

```css
header .logo a img {display:block;}
```

for 

```css
header .logo a img {display:block; height:100%}
```

**Comment by jfoclpf** [comment]
```css
header .logo a img {display:block; height:100%;}
```

I already tested this in IE and it works fine, being the only issue in IE 11
